"""
SQLAlchemy ORM models for the Vocabulary Assistant.
Defines: words, reviews, learning_records, users tables.
"""

from sqlalchemy import (
    Column, Integer, String, Text, DateTime, Float, 
    ForeignKey, JSON, Boolean, create_engine
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from backend.database.connection import Base


class User(Base):
    """User model for multi-user support."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    telegram_id = Column(String(50), unique=True, index=True, nullable=True)
    username = Column(String(100), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    words = relationship("Word", back_populates="user", cascade="all, delete-orphan")
    reviews = relationship("Review", back_populates="user", cascade="all, delete-orphan")
    learning_records = relationship("LearningRecord", back_populates="user", cascade="all, delete-orphan")


class Word(Base):
    """Vocabulary word entry with full details."""
    __tablename__ = "words"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    # Core fields
    word = Column(String(200), nullable=False, index=True)
    phonetic = Column(String(200), nullable=True)  # IPA phonetic symbol
    part_of_speech = Column(String(100), nullable=True)  # noun, verb, adj, etc.
    chinese_meaning = Column(Text, nullable=True)

    # Example sentence (from real sources)
    example_sentence = Column(Text, nullable=True)
    chinese_translation = Column(Text, nullable=True)

    # Source information
    source_name = Column(String(200), nullable=True)  # Reuters, BBC, etc.
    source_url = Column(Text, nullable=True)  # Original article URL

    # Optional fields
    audio_url = Column(Text, nullable=True)  # TTS audio file URL
    tags = Column(JSON, nullable=True)  # ["business", "politics"]

    # Extended vocabulary info (auto-generated by VocabTutor Agent)
    collocations = Column(JSON, nullable=True)  # ["abandon ship", "abandon hope"]
    synonyms = Column(JSON, nullable=True)  # ["desert", "forsake"]
    antonyms = Column(JSON, nullable=True)  # ["retain", "keep"]

    # Learning metadata
    difficulty = Column(Integer, default=1)  # 1-5 scale
    learned = Column(Boolean, default=False)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="words")
    reviews = relationship("Review", back_populates="word", cascade="all, delete-orphan")
    learning_records = relationship("LearningRecord", back_populates="word", cascade="all, delete-orphan")


class Review(Base):
    """Spaced repetition review record (SM-2 algorithm)."""
    __tablename__ = "reviews"

    id = Column(Integer, primary_key=True, index=True)
    word_id = Column(Integer, ForeignKey("words.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    # SM-2 algorithm fields
    review_date = Column(DateTime(timezone=True), server_default=func.now())
    next_review_date = Column(DateTime(timezone=True), nullable=True)
    interval = Column(Integer, default=1)  # Days until next review
    ease_factor = Column(Float, default=2.5)  # SM-2 ease factor
    repetitions = Column(Integer, default=0)  # Number of successful reviews

    # Quality rating: 0-5 (5=perfect, 0=complete blackout)
    quality = Column(Integer, nullable=True)

    # Review session info
    is_due = Column(Boolean, default=True)
    reviewed_count = Column(Integer, default=0)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    word = relationship("Word", back_populates="reviews")
    user = relationship("User", back_populates="reviews")


class LearningRecord(Base):
    """Tracks all learning activities for statistics."""
    __tablename__ = "learning_records"

    id = Column(Integer, primary_key=True, index=True)
    word_id = Column(Integer, ForeignKey("words.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    # Action type: added, reviewed, quizzed, audio_played
    action = Column(String(50), nullable=False)
    score = Column(Integer, nullable=True)  # Quiz score or quality rating
    details = Column(JSON, nullable=True)  # Extra metadata

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    word = relationship("Word", back_populates="learning_records")
    user = relationship("User", back_populates="learning_records")


class DailyStats(Base):
    """Daily learning statistics aggregation."""
    __tablename__ = "daily_stats"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    date = Column(String(10), nullable=False)  # YYYY-MM-DD

    words_added = Column(Integer, default=0)
    words_reviewed = Column(Integer, default=0)
    words_learned = Column(Integer, default=0)
    quiz_score_avg = Column(Float, default=0.0)
    study_minutes = Column(Integer, default=0)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
